# WEB SCRAPING
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RMTdEOZa6kNL12ooFBGGjh_r1E_S18T2
"""

import requests

import urllib.request
from bs4 import BeautifulSoup

response = urllib.request.urlopen("https://en.wikipedia.org/wiki/Nikola_Tesla")
htmlFormat = response.read()
print(htmlFormat)

'''soup = BeautifulSoup(htmlFormat, 'html5lib')
text = soup.get_text(strip = True)
tokens = [t for t in text.split()]
clean_tokens = tokens[:]
print(tokens)'''

'''import requests
import bs4
res = requests.get("https://quotes.toscrape.com/")
res.text
soup = bs4.BeautifulSoup(res.text,'lxml')
print(soup.select(".author"))'''

'''authors = set()
for name in soup.select(".author"):
  authors.add(name.text)
print(authors)'''

'''quotes = []
for quote in soup.select(".text"):
  quotes.append(quote.text)
print(quotes)'''

'''soup = bs4.BeautifulSoup(res.text,'lxml')
soup.select('.tag-item')
for item in soup.select(".tag-item"):
  print(item.text)'''